spring:
  application:
    name: fp-labs-wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    # Apagamos la creación automática de tablas (ddl-auto) porque
    # nuestra arquitectura dicta que la base de datos la creamos nosotros a mano.
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
